# -*- coding: utf-8 -*-
#
# Configuration file for the Sphinx documentation builder.
#
# This file does only contain a selection of the most common options. For a
# full list see the documentation:
# http://www.sphinx-doc.org/en/master/config

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))


# -- Project information -----------------------------------------------------

project = 'report'
copyright = '2019, fumuumuf'
document_title = 'ふーむのどきゅめんと'
author = '河合 ふーむ'

# The short X.Y version
version = ''
# The full version, including alpha/beta/rc tags
release = ''

# -- General configuration ---------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.mathjax',
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'ja'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path .
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'alabaster'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
# html_theme_options = {}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# The default sidebars (for documents that don't match any pattern) are
# defined by theme itself.  Builtin themes are using these templates by
# default: ``['localtoc.html', 'relations.html', 'sourcelink.html',
# 'searchbox.html']``.
#
# html_sidebars = {}


# -- Options for HTMLHelp output ---------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'reportdoc'

# -- Options for LaTeX output ------------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'report.tex', document_title,
     author, 'manual'),
]

# -- Options for manual page output ------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'report', document_title,
     [author], 1)
]

# -- Options for Texinfo output ----------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'report', document_title,
     author, 'report', 'One line description of project.',
     'Miscellaneous'),
]

numfig = True

# -- Extension configuration -------------------------------------------------
# -- LaTexの設定 --------------------------------------------------------------

# LaTeX の docclass 設定
latex_docclass = {'manual': 'jsbook'}
latex_paper_size = 'a4'

# 目次設定 表示したくないのでブランクでクリアしている
HIDE_TABLE_OF_CONTENTS = True
if HIDE_TABLE_OF_CONTENTS:
    latex_elements['tableofcontents'] = r''' 
    '''

# 表紙の後に空白ベージ産まないように
latex_elements['extraclassoptions'] = 'openany'

# preambleの設定
latex_elements['preamble'] = r"""

\usepackage{titlesec}
\usepackage{picture}
\usepackage{graphicx}

% --------------------------------------
% -- chapter, sectionのレイアウト制御 --
% --------------------------------------

% chapter
\titlespacing{\chapter}{0pt}{*-2}{*2} % chapterの余白を制御

% chapter はドキュメントクラスに定義された @omit@number を参照したいので makeatletter - makeatother で囲っている
% これは 参考文献にはこの chapter 設定を適用しないようにするため.
\makeatletter
\titleformat{\chapter}[block]
{\huge} % 書式
{\huge} % ラベル書式
{0pt} % ラベルと見出しの間隔
{ % 見出し直前コード
  \hspace{-12pt}
  \hspace{0pt}
  \if@omit@number
  \else
  {\filleft \thechapter.} % chapter 番号
  \fi
} 
[ % 見出し直後コード
  \hrule 
] 
\makeatother

% section
\titleformat{\section}[block]
{}{}{0pt}
{
  \hspace{-5pt}
  % \normalfont \large\bfseries \thesection
  \normalfont \large\bfseries
}
[ 
\vspace{-10pt}
]

% subsection
\titleformat{\subsection}[block]
{}{}{0pt}
{
  \hspace{-5pt}
  % \normalfont \Large\bfseries \thesubsection
  \bfseries(\roman{subsection}) 
}
[
\vspace{-5pt}
]

% ----------------------------
% -- 表紙の簡素化 ------------
% ----------------------------

\makeatletter 
\renewcommand{\maketitle}{%
  \let\spx@tempa\relax
  \ifHy@pageanchor\def\spx@tempa{\Hy@pageanchortrue}\fi
  \hypersetup{pageanchor=false}% avoid duplicate destination 
  \begin{titlepage}%
    \let\footnotesize\small
    \let\footnoterule\relax
    \noindent\rule{\textwidth}{1pt}\par % 罫線
    
    \begin{center}%
      \vfill
      \sphinxlogo
      \py@HeaderFamily
      {\Huge \@title \par}
      {\itshape\LARGE \py@release\releaseinfo \par}
      \vfill
    \end{center}%\par
    \begin{flushright}%
      {\LARGE
        \begin{tabular}[t]{l}
          \gakunen \\
          \@author
        \end{tabular}
        \par}
      %\vfill\vfill
    \end{flushright}%
    \@thanks
  \end{titlepage}%
}
\makeatletter 


% --------------------------------
% -- ページのスタイル制御 --
% --------------------------------

% ここではフッターにページ番号を表示するだけのシンプルな設定をする. 

\pagenumbering{arabic} % ページ番号をアラビア数字に

% plain ページスタイルの再定義
\fancypagestyle{plain}{
\fancyhf{} % 一旦設定をクリア
\fancyfoot[CE,CO]{\thepage}
\renewcommand{\headrulewidth}{0pt}
\renewcommand{\footrulewidth}{0.4pt}
}

% sphinx > 1.8.1 では section の無いページは plain ではなくこちらの設定が反映される
\fancypagestyle{normal}{
\fancyhf{} % 一旦設定をクリア
\fancyfoot[CE,CO]{\thepage}
\renewcommand{\headrulewidth}{0pt}
\renewcommand{\footrulewidth}{0.4pt}
}

% jsclasses/jsreport.cls ではchapterの開始ページは plainhead (or plainfoot) になる
\fancypagestyle{plainhead}{
\fancyhf{} % 一旦設定をクリア
\fancyfoot[CE,CO]{\thepage}
\renewcommand{\headrulewidth}{0pt}
\renewcommand{\footrulewidth}{0.4pt}
}

% plainhead だけで良さそうだったけど, 念の為定義
\fancypagestyle{plainfoot}{
\fancyhf{} % 一旦設定をクリア
\fancyfoot[CE,CO]{\thepage}
\renewcommand{\headrulewidth}{0pt}
\renewcommand{\footrulewidth}{0.4pt}
}

\pagestyle{plain} % ページスタイルを plain に変更 

% --------------------------
% ------- その他 -----------
% --------------------------

% 段落の字下げ
\setlength\parindent{1zw} 

% 1ページクリアして 参考文献の出力 (デフォルトだと 中1ページ挿入)
\renewenvironment{sphinxthebibliography}[1]
{\clearpage 
 \begin{thebibliography}{1}}
{\end{thebibliography}}

% プリントアウトするときは有効に
% \hypersetup{colorlinks=false} % ハイパーリンクの色を無効にする

% 図番を chapter で区切らず通しに
% \makeatletter
% \renewcommand{\thefigure}{%
% \arabic{figure}}
% \renewcommand{\thetable}{%
% \arabic{table}}
% \makeatother

"""

latex_elements['preamble'] += r"""
\def\gakunen{3年1組}
"""

